name: docker-nginx
on:
  push:
    branches: 
      - master
    paths:
      # - 'opencv-debian.Dockerfile'
      - 'Dockerfile'


jobs:
  docker-nginx:
    runs-on: ubuntu-latest
    name: builx docker-nginx
    steps:
      # https://github.com/marketplace/actions/customizable-docker-buildx
      - name: Checkout master
        uses: actions/checkout@master
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: doubledong/docker-nginx
          tag: 1.19
          dockerHubUser: ${{ secrets.DOCKER_USERNAME }}
          dockerHubPassword: ${{ secrets.DOCKER_PASSWORD }}
          platform: linux/amd64,linux/arm64
          dockerFile: Dockerfile
